// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFYWw3qBun9Js9_hmF_E6nD4Z6Hg5AAA',
    appId: '1:973811964325:web:79b718aba707fb0540704c',
    messagingSenderId: '973811964325',
    projectId: 'protes-17280',
    authDomain: 'protes-17280.firebaseapp.com',
    storageBucket: 'protes-17280.appspot.com',
    measurementId: 'G-6NYN4D4GWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALc5m5JfqCEu1Ejqjs5qQqXEZvWSNqXg4',
    appId: '1:973811964325:android:337c69316b42afb540704c',
    messagingSenderId: '973811964325',
    projectId: 'protes-17280',
    storageBucket: 'protes-17280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gGPeI7lF2yaBREAP7OYAKymZJ08E2_E',
    appId: '1:973811964325:ios:87e5e1b722e158fb40704c',
    messagingSenderId: '973811964325',
    projectId: 'protes-17280',
    storageBucket: 'protes-17280.appspot.com',
    iosClientId: '973811964325-6s48hmrinr4o8jbhm5unmptdqcf6d8hi.apps.googleusercontent.com',
    iosBundleId: 'com.devspot.protes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8gGPeI7lF2yaBREAP7OYAKymZJ08E2_E',
    appId: '1:973811964325:ios:87e5e1b722e158fb40704c',
    messagingSenderId: '973811964325',
    projectId: 'protes-17280',
    storageBucket: 'protes-17280.appspot.com',
    iosClientId: '973811964325-6s48hmrinr4o8jbhm5unmptdqcf6d8hi.apps.googleusercontent.com',
    iosBundleId: 'com.devspot.protes',
  );
}
